package net.iretailer.model;
// Generated 2016-2-1 23:19:37 by Hibernate Tools 4.3.1.Final

/**
 * DAlarmPolicy generated by hbm2java
 */
public class DAlarmPolicy implements java.io.Serializable {

	private String id;
	private String alarmCode;
	private String method;
	private Integer minCount;
	private Integer repeatCount;
	private String alarmLevel;

	public DAlarmPolicy() {
	}

	public DAlarmPolicy(String id, String alarmCode, String method) {
		this.id = id;
		this.alarmCode = alarmCode;
		this.method = method;
	}

	public DAlarmPolicy(String id, String alarmCode, String method, Integer minCount, Integer repeatCount,
			String alarmLevel) {
		this.id = id;
		this.alarmCode = alarmCode;
		this.method = method;
		this.minCount = minCount;
		this.repeatCount = repeatCount;
		this.alarmLevel = alarmLevel;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getAlarmCode() {
		return this.alarmCode;
	}

	public void setAlarmCode(String alarmCode) {
		this.alarmCode = alarmCode;
	}

	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	public Integer getMinCount() {
		return this.minCount;
	}

	public void setMinCount(Integer minCount) {
		this.minCount = minCount;
	}

	public Integer getRepeatCount() {
		return this.repeatCount;
	}

	public void setRepeatCount(Integer repeatCount) {
		this.repeatCount = repeatCount;
	}

	public String getAlarmLevel() {
		return this.alarmLevel;
	}

	public void setAlarmLevel(String alarmLevel) {
		this.alarmLevel = alarmLevel;
	}

}
