package net.iretailer.model;
// Generated 2016-2-1 23:19:37 by Hibernate Tools 4.3.1.Final

/**
 * DAlarmMethod generated by hbm2java
 */
public class DAlarmMethod implements java.io.Serializable {

	private String id;
	private String name;
	private String method;
	private String server;
	private String port;
	private String userName;
	private String userPass;

	public DAlarmMethod() {
	}

	public DAlarmMethod(String id, String name, String method) {
		this.id = id;
		this.name = name;
		this.method = method;
	}

	public DAlarmMethod(String id, String name, String method, String server, String port, String userName,
			String userPass) {
		this.id = id;
		this.name = name;
		this.method = method;
		this.server = server;
		this.port = port;
		this.userName = userName;
		this.userPass = userPass;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	public String getServer() {
		return this.server;
	}

	public void setServer(String server) {
		this.server = server;
	}

	public String getPort() {
		return this.port;
	}

	public void setPort(String port) {
		this.port = port;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPass() {
		return this.userPass;
	}

	public void setUserPass(String userPass) {
		this.userPass = userPass;
	}

}
