package net.iretailer.model;
// Generated 2016-2-1 23:19:37 by Hibernate Tools 4.3.1.Final

/**
 * DAlarm generated by hbm2java
 */
public class DAlarm implements java.io.Serializable {

	private String id;
	private String code;
	private String description;
	private String keys;
	private String name;

	public DAlarm() {
	}

	public DAlarm(String id, String code, String description, String name) {
		this.id = id;
		this.code = code;
		this.description = description;
		this.name = name;
	}

	public DAlarm(String id, String code, String description, String keys, String name) {
		this.id = id;
		this.code = code;
		this.description = description;
		this.keys = keys;
		this.name = name;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getKeys() {
		return this.keys;
	}

	public void setKeys(String keys) {
		this.keys = keys;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
