package net.iretailer.model;
// Generated 2016-2-1 23:19:37 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Device generated by hbm2java
 */
public class Device implements java.io.Serializable {

	private Integer id;
	private String storeId;
	private String name;
	private String deviceNameId;
	private String ipaddr;
	private String macaddr;
	private short channelId;
	private boolean enabled;
	private String deviceType;
	private Short rssienter;
	private Date updateTime;

	public Device() {
	}

	public Device(short channelId, boolean enabled) {
		this.channelId = channelId;
		this.enabled = enabled;
	}

	public Device(String storeId, String name, String deviceNameId, String ipaddr, String macaddr, short channelId,
			boolean enabled, String deviceType, Short rssienter, Date updateTime) {
		this.storeId = storeId;
		this.name = name;
		this.deviceNameId = deviceNameId;
		this.ipaddr = ipaddr;
		this.macaddr = macaddr;
		this.channelId = channelId;
		this.enabled = enabled;
		this.deviceType = deviceType;
		this.rssienter = rssienter;
		this.updateTime = updateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStoreId() {
		return this.storeId;
	}

	public void setStoreId(String storeId) {
		this.storeId = storeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDeviceNameId() {
		return this.deviceNameId;
	}

	public void setDeviceNameId(String deviceNameId) {
		this.deviceNameId = deviceNameId;
	}

	public String getIpaddr() {
		return this.ipaddr;
	}

	public void setIpaddr(String ipaddr) {
		this.ipaddr = ipaddr;
	}

	public String getMacaddr() {
		return this.macaddr;
	}

	public void setMacaddr(String macaddr) {
		this.macaddr = macaddr;
	}

	public short getChannelId() {
		return this.channelId;
	}

	public void setChannelId(short channelId) {
		this.channelId = channelId;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public String getDeviceType() {
		return this.deviceType;
	}

	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType;
	}

	public Short getRssienter() {
		return this.rssienter;
	}

	public void setRssienter(Short rssienter) {
		this.rssienter = rssienter;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
