package net.iretailer.model;
// Generated 2016-2-1 23:19:37 by Hibernate Tools 4.3.1.Final

/**
 * DLocation generated by hbm2java
 */
public class DLocation implements java.io.Serializable {

	private String id;
	private String name;
	private Integer level;
	private String parentId;
	private String imageUrl;
	private Integer getWeather;
	private String cityCode1;
	private String cityCode2;
	private int rank;
	private Integer visible;
	private String updateUser;
	private String updateTime;
	private int deleteFlag;

	public DLocation() {
	}

	public DLocation(String id, String parentId, int rank, int deleteFlag) {
		this.id = id;
		this.parentId = parentId;
		this.rank = rank;
		this.deleteFlag = deleteFlag;
	}

	public DLocation(String id, String name, Integer level, String parentId, String imageUrl, Integer getWeather,
			String cityCode1, String cityCode2, int rank, Integer visible, String updateUser, String updateTime,
			int deleteFlag) {
		this.id = id;
		this.name = name;
		this.level = level;
		this.parentId = parentId;
		this.imageUrl = imageUrl;
		this.getWeather = getWeather;
		this.cityCode1 = cityCode1;
		this.cityCode2 = cityCode2;
		this.rank = rank;
		this.visible = visible;
		this.updateUser = updateUser;
		this.updateTime = updateTime;
		this.deleteFlag = deleteFlag;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	public Integer getGetWeather() {
		return this.getWeather;
	}

	public void setGetWeather(Integer getWeather) {
		this.getWeather = getWeather;
	}

	public String getCityCode1() {
		return this.cityCode1;
	}

	public void setCityCode1(String cityCode1) {
		this.cityCode1 = cityCode1;
	}

	public String getCityCode2() {
		return this.cityCode2;
	}

	public void setCityCode2(String cityCode2) {
		this.cityCode2 = cityCode2;
	}

	public int getRank() {
		return this.rank;
	}

	public void setRank(int rank) {
		this.rank = rank;
	}

	public Integer getVisible() {
		return this.visible;
	}

	public void setVisible(Integer visible) {
		this.visible = visible;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public String getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

	public int getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(int deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

}
