package net.iretailer.model;
// Generated 2016-2-1 23:19:37 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * DStore generated by hbm2java
 */
public class DStore implements java.io.Serializable {

	private String id;
	private String storeName;
	private String shortName;
	private Integer siteId;
	private String storeRegionId;
	private String storeProvinceId;
	private String storeCityId;
	private String storeDistrictId;
	private String address;
	private String clerkNumber;
	private String operationAcreage;
	private String rentTypeId;
	private Integer rentCost;
	private BigDecimal discount;
	private String createTime;
	private String createUser;
	private String updateTime;
	private String updateUser;
	private Integer deleteFlag;

	public DStore() {
	}

	public DStore(String id) {
		this.id = id;
	}

	public DStore(String id, String storeName, String shortName, Integer siteId, String storeRegionId,
			String storeProvinceId, String storeCityId, String storeDistrictId, String address, String clerkNumber,
			String operationAcreage, String rentTypeId, Integer rentCost, BigDecimal discount, String createTime,
			String createUser, String updateTime, String updateUser, Integer deleteFlag) {
		this.id = id;
		this.storeName = storeName;
		this.shortName = shortName;
		this.siteId = siteId;
		this.storeRegionId = storeRegionId;
		this.storeProvinceId = storeProvinceId;
		this.storeCityId = storeCityId;
		this.storeDistrictId = storeDistrictId;
		this.address = address;
		this.clerkNumber = clerkNumber;
		this.operationAcreage = operationAcreage;
		this.rentTypeId = rentTypeId;
		this.rentCost = rentCost;
		this.discount = discount;
		this.createTime = createTime;
		this.createUser = createUser;
		this.updateTime = updateTime;
		this.updateUser = updateUser;
		this.deleteFlag = deleteFlag;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getStoreName() {
		return this.storeName;
	}

	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}

	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public Integer getSiteId() {
		return this.siteId;
	}

	public void setSiteId(Integer siteId) {
		this.siteId = siteId;
	}

	public String getStoreRegionId() {
		return this.storeRegionId;
	}

	public void setStoreRegionId(String storeRegionId) {
		this.storeRegionId = storeRegionId;
	}

	public String getStoreProvinceId() {
		return this.storeProvinceId;
	}

	public void setStoreProvinceId(String storeProvinceId) {
		this.storeProvinceId = storeProvinceId;
	}

	public String getStoreCityId() {
		return this.storeCityId;
	}

	public void setStoreCityId(String storeCityId) {
		this.storeCityId = storeCityId;
	}

	public String getStoreDistrictId() {
		return this.storeDistrictId;
	}

	public void setStoreDistrictId(String storeDistrictId) {
		this.storeDistrictId = storeDistrictId;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getClerkNumber() {
		return this.clerkNumber;
	}

	public void setClerkNumber(String clerkNumber) {
		this.clerkNumber = clerkNumber;
	}

	public String getOperationAcreage() {
		return this.operationAcreage;
	}

	public void setOperationAcreage(String operationAcreage) {
		this.operationAcreage = operationAcreage;
	}

	public String getRentTypeId() {
		return this.rentTypeId;
	}

	public void setRentTypeId(String rentTypeId) {
		this.rentTypeId = rentTypeId;
	}

	public Integer getRentCost() {
		return this.rentCost;
	}

	public void setRentCost(Integer rentCost) {
		this.rentCost = rentCost;
	}

	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public String getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public Integer getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Integer deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

}
