package net.iretailer.model;
// Generated 2016-2-1 23:19:37 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Dwelltime generated by hbm2java
 */
public class Dwelltime implements java.io.Serializable {

	private Integer id;
	private int zoneId;
	private Date starTime;
	private String date;
	private Short dateHour;
	private Short dateMin;
	private Short numberServed;
	private Short secondsOccupied;

	public Dwelltime() {
	}

	public Dwelltime(int zoneId) {
		this.zoneId = zoneId;
	}

	public Dwelltime(int zoneId, Date starTime, String date, Short dateHour, Short dateMin, Short numberServed,
			Short secondsOccupied) {
		this.zoneId = zoneId;
		this.starTime = starTime;
		this.date = date;
		this.dateHour = dateHour;
		this.dateMin = dateMin;
		this.numberServed = numberServed;
		this.secondsOccupied = secondsOccupied;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getZoneId() {
		return this.zoneId;
	}

	public void setZoneId(int zoneId) {
		this.zoneId = zoneId;
	}

	public Date getStarTime() {
		return this.starTime;
	}

	public void setStarTime(Date starTime) {
		this.starTime = starTime;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public Short getDateHour() {
		return this.dateHour;
	}

	public void setDateHour(Short dateHour) {
		this.dateHour = dateHour;
	}

	public Short getDateMin() {
		return this.dateMin;
	}

	public void setDateMin(Short dateMin) {
		this.dateMin = dateMin;
	}

	public Short getNumberServed() {
		return this.numberServed;
	}

	public void setNumberServed(Short numberServed) {
		this.numberServed = numberServed;
	}

	public Short getSecondsOccupied() {
		return this.secondsOccupied;
	}

	public void setSecondsOccupied(Short secondsOccupied) {
		this.secondsOccupied = secondsOccupied;
	}

}
