package net.iretailer.model;
// Generated 2016-2-1 23:19:37 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * MtPackDwelltime generated by hbm2java
 */
public class MtPackDwelltime implements java.io.Serializable {

	private Integer id;
	private int zoneId;
	private String date;
	private Short dateHour;
	private Short dateMinPeriod;
	private Short numberServed;
	private Short secondsOccupied;
	private Date packTime;
	private Date updateTime;
	private Short period;

	public MtPackDwelltime() {
	}

	public MtPackDwelltime(int zoneId) {
		this.zoneId = zoneId;
	}

	public MtPackDwelltime(int zoneId, String date, Short dateHour, Short dateMinPeriod, Short numberServed,
			Short secondsOccupied, Date packTime, Date updateTime, Short period) {
		this.zoneId = zoneId;
		this.date = date;
		this.dateHour = dateHour;
		this.dateMinPeriod = dateMinPeriod;
		this.numberServed = numberServed;
		this.secondsOccupied = secondsOccupied;
		this.packTime = packTime;
		this.updateTime = updateTime;
		this.period = period;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getZoneId() {
		return this.zoneId;
	}

	public void setZoneId(int zoneId) {
		this.zoneId = zoneId;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public Short getDateHour() {
		return this.dateHour;
	}

	public void setDateHour(Short dateHour) {
		this.dateHour = dateHour;
	}

	public Short getDateMinPeriod() {
		return this.dateMinPeriod;
	}

	public void setDateMinPeriod(Short dateMinPeriod) {
		this.dateMinPeriod = dateMinPeriod;
	}

	public Short getNumberServed() {
		return this.numberServed;
	}

	public void setNumberServed(Short numberServed) {
		this.numberServed = numberServed;
	}

	public Short getSecondsOccupied() {
		return this.secondsOccupied;
	}

	public void setSecondsOccupied(Short secondsOccupied) {
		this.secondsOccupied = secondsOccupied;
	}

	public Date getPackTime() {
		return this.packTime;
	}

	public void setPackTime(Date packTime) {
		this.packTime = packTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public Short getPeriod() {
		return this.period;
	}

	public void setPeriod(Short period) {
		this.period = period;
	}

}
