package net.iretailer.model;
// Generated 2016-2-1 23:19:37 by Hibernate Tools 4.3.1.Final

/**
 * Physicalzone generated by hbm2java
 */
public class Physicalzone implements java.io.Serializable {

	private Integer id;
	private String storeId;
	private Integer siteId;
	private String name;
	private String zoneTypeId;
	private Short enable;
	private String floor;
	private Short reverseBak;
	private Short overload;

	public Physicalzone() {
	}

	public Physicalzone(String storeId) {
		this.storeId = storeId;
	}

	public Physicalzone(String storeId, Integer siteId, String name, String zoneTypeId, Short enable, String floor,
			Short reverseBak, Short overload) {
		this.storeId = storeId;
		this.siteId = siteId;
		this.name = name;
		this.zoneTypeId = zoneTypeId;
		this.enable = enable;
		this.floor = floor;
		this.reverseBak = reverseBak;
		this.overload = overload;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStoreId() {
		return this.storeId;
	}

	public void setStoreId(String storeId) {
		this.storeId = storeId;
	}

	public Integer getSiteId() {
		return this.siteId;
	}

	public void setSiteId(Integer siteId) {
		this.siteId = siteId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getZoneTypeId() {
		return this.zoneTypeId;
	}

	public void setZoneTypeId(String zoneTypeId) {
		this.zoneTypeId = zoneTypeId;
	}

	public Short getEnable() {
		return this.enable;
	}

	public void setEnable(Short enable) {
		this.enable = enable;
	}

	public String getFloor() {
		return this.floor;
	}

	public void setFloor(String floor) {
		this.floor = floor;
	}

	public Short getReverseBak() {
		return this.reverseBak;
	}

	public void setReverseBak(Short reverseBak) {
		this.reverseBak = reverseBak;
	}

	public Short getOverload() {
		return this.overload;
	}

	public void setOverload(Short overload) {
		this.overload = overload;
	}

}
