package net.iretailer.model;
// Generated 2016-2-1 23:19:37 by Hibernate Tools 4.3.1.Final

/**
 * RPhysicalzoneZone generated by hbm2java
 */
public class RPhysicalzoneZone implements java.io.Serializable {

	private Integer id;
	private int physicalzoneId;
	private int zoneId;
	private Short reverse;
	private String deviceType;

	public RPhysicalzoneZone() {
	}

	public RPhysicalzoneZone(int physicalzoneId, int zoneId) {
		this.physicalzoneId = physicalzoneId;
		this.zoneId = zoneId;
	}

	public RPhysicalzoneZone(int physicalzoneId, int zoneId, Short reverse, String deviceType) {
		this.physicalzoneId = physicalzoneId;
		this.zoneId = zoneId;
		this.reverse = reverse;
		this.deviceType = deviceType;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getPhysicalzoneId() {
		return this.physicalzoneId;
	}

	public void setPhysicalzoneId(int physicalzoneId) {
		this.physicalzoneId = physicalzoneId;
	}

	public int getZoneId() {
		return this.zoneId;
	}

	public void setZoneId(int zoneId) {
		this.zoneId = zoneId;
	}

	public Short getReverse() {
		return this.reverse;
	}

	public void setReverse(Short reverse) {
		this.reverse = reverse;
	}

	public String getDeviceType() {
		return this.deviceType;
	}

	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType;
	}

}
