package net.iretailer.model;
// Generated 2016-2-1 23:19:37 by Hibernate Tools 4.3.1.Final

/**
 * SCategory generated by hbm2java
 */
public class SCategory implements java.io.Serializable {

	private String id;
	private String name;
	private String keyName;
	private String data;
	private String parentId;
	private String imageUrl;
	private int rank;
	private String updateUser;
	private String updateTime;
	private int deleteFlag;
	private String remark;

	public SCategory() {
	}

	public SCategory(String id, String parentId, int rank, int deleteFlag) {
		this.id = id;
		this.parentId = parentId;
		this.rank = rank;
		this.deleteFlag = deleteFlag;
	}

	public SCategory(String id, String name, String keyName, String data, String parentId, String imageUrl, int rank,
			String updateUser, String updateTime, int deleteFlag, String remark) {
		this.id = id;
		this.name = name;
		this.keyName = keyName;
		this.data = data;
		this.parentId = parentId;
		this.imageUrl = imageUrl;
		this.rank = rank;
		this.updateUser = updateUser;
		this.updateTime = updateTime;
		this.deleteFlag = deleteFlag;
		this.remark = remark;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getKeyName() {
		return this.keyName;
	}

	public void setKeyName(String keyName) {
		this.keyName = keyName;
	}

	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	public int getRank() {
		return this.rank;
	}

	public void setRank(int rank) {
		this.rank = rank;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public String getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

	public int getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(int deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
