package net.iretailer.model;
// Generated 2016-2-1 23:19:37 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * SPlatformLog generated by hbm2java
 */
public class SPlatformLog implements java.io.Serializable {

	private Integer id;
	private Date date;
	private String logType;
	private String userCode;
	private String userIp;
	private String operate;
	private String operateTarget;
	private short operateResult;
	private String pageUrl;
	private String pageOperate;
	private String message;
	private String exception;

	public SPlatformLog() {
	}

	public SPlatformLog(Date date, String userIp, String operate, short operateResult, String pageUrl) {
		this.date = date;
		this.userIp = userIp;
		this.operate = operate;
		this.operateResult = operateResult;
		this.pageUrl = pageUrl;
	}

	public SPlatformLog(Date date, String logType, String userCode, String userIp, String operate, String operateTarget,
			short operateResult, String pageUrl, String pageOperate, String message, String exception) {
		this.date = date;
		this.logType = logType;
		this.userCode = userCode;
		this.userIp = userIp;
		this.operate = operate;
		this.operateTarget = operateTarget;
		this.operateResult = operateResult;
		this.pageUrl = pageUrl;
		this.pageOperate = pageOperate;
		this.message = message;
		this.exception = exception;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getLogType() {
		return this.logType;
	}

	public void setLogType(String logType) {
		this.logType = logType;
	}

	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	public String getOperate() {
		return this.operate;
	}

	public void setOperate(String operate) {
		this.operate = operate;
	}

	public String getOperateTarget() {
		return this.operateTarget;
	}

	public void setOperateTarget(String operateTarget) {
		this.operateTarget = operateTarget;
	}

	public short getOperateResult() {
		return this.operateResult;
	}

	public void setOperateResult(short operateResult) {
		this.operateResult = operateResult;
	}

	public String getPageUrl() {
		return this.pageUrl;
	}

	public void setPageUrl(String pageUrl) {
		this.pageUrl = pageUrl;
	}

	public String getPageOperate() {
		return this.pageOperate;
	}

	public void setPageOperate(String pageOperate) {
		this.pageOperate = pageOperate;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getException() {
		return this.exception;
	}

	public void setException(String exception) {
		this.exception = exception;
	}

}
