package net.iretailer.model;
// Generated 2016-2-1 23:19:37 by Hibernate Tools 4.3.1.Final

/**
 * SrUserStore generated by hbm2java
 */
public class SrUserStore implements java.io.Serializable {

	private String id;
	private String userId;
	private String storeId;

	public SrUserStore() {
	}

	public SrUserStore(String id, String userId, String storeId) {
		this.id = id;
		this.userId = userId;
		this.storeId = storeId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getStoreId() {
		return this.storeId;
	}

	public void setStoreId(String storeId) {
		this.storeId = storeId;
	}

}
