package net.iretailer.model;
// Generated 2016-2-1 23:19:37 by Hibernate Tools 4.3.1.Final

/**
 * SUser generated by hbm2java
 */
public class SUser implements java.io.Serializable {

	private String id;
	private int accountNo;
	private String userCode;
	private String userPwd;
	private String name;
	private String roleId;
	private String email;
	private String mobile;
	private String telephone;
	private Short tryTimes;
	private Short isLock;
	private String lockTime;
	private String createUser;
	private String createTime;
	private String updateUser;
	private String updateTime;
	private int deleteFlag;

	public SUser() {
	}

	public SUser(String id, int accountNo, String userCode, String userPwd, String name, String roleId,
			String createTime, String updateTime, int deleteFlag) {
		this.id = id;
		this.accountNo = accountNo;
		this.userCode = userCode;
		this.userPwd = userPwd;
		this.name = name;
		this.roleId = roleId;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.deleteFlag = deleteFlag;
	}

	public SUser(String id, int accountNo, String userCode, String userPwd, String name, String roleId, String email,
			String mobile, String telephone, Short tryTimes, Short isLock, String lockTime, String createUser,
			String createTime, String updateUser, String updateTime, int deleteFlag) {
		this.id = id;
		this.accountNo = accountNo;
		this.userCode = userCode;
		this.userPwd = userPwd;
		this.name = name;
		this.roleId = roleId;
		this.email = email;
		this.mobile = mobile;
		this.telephone = telephone;
		this.tryTimes = tryTimes;
		this.isLock = isLock;
		this.lockTime = lockTime;
		this.createUser = createUser;
		this.createTime = createTime;
		this.updateUser = updateUser;
		this.updateTime = updateTime;
		this.deleteFlag = deleteFlag;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public int getAccountNo() {
		return this.accountNo;
	}

	public void setAccountNo(int accountNo) {
		this.accountNo = accountNo;
	}

	public String getUserCode() {
		return this.userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	public String getUserPwd() {
		return this.userPwd;
	}

	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public Short getTryTimes() {
		return this.tryTimes;
	}

	public void setTryTimes(Short tryTimes) {
		this.tryTimes = tryTimes;
	}

	public Short getIsLock() {
		return this.isLock;
	}

	public void setIsLock(Short isLock) {
		this.isLock = isLock;
	}

	public String getLockTime() {
		return this.lockTime;
	}

	public void setLockTime(String lockTime) {
		this.lockTime = lockTime;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public String getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	public String getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

	public int getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(int deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

}
