package net.iretailer.model;
// Generated 2016-2-1 23:19:37 by Hibernate Tools 4.3.1.Final

/**
 * TAutoRun generated by hbm2java
 */
public class TAutoRun implements java.io.Serializable {

	private String id;
	private String configName;
	private String service;
	private Integer runAtStart;
	private String runTime;
	private String tickPeriod;
	private Integer tickTime;
	private String weekdays;
	private String description;
	private Integer enabled;

	public TAutoRun() {
	}

	public TAutoRun(String id, String configName, String service) {
		this.id = id;
		this.configName = configName;
		this.service = service;
	}

	public TAutoRun(String id, String configName, String service, Integer runAtStart, String runTime, String tickPeriod,
			Integer tickTime, String weekdays, String description, Integer enabled) {
		this.id = id;
		this.configName = configName;
		this.service = service;
		this.runAtStart = runAtStart;
		this.runTime = runTime;
		this.tickPeriod = tickPeriod;
		this.tickTime = tickTime;
		this.weekdays = weekdays;
		this.description = description;
		this.enabled = enabled;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getConfigName() {
		return this.configName;
	}

	public void setConfigName(String configName) {
		this.configName = configName;
	}

	public String getService() {
		return this.service;
	}

	public void setService(String service) {
		this.service = service;
	}

	public Integer getRunAtStart() {
		return this.runAtStart;
	}

	public void setRunAtStart(Integer runAtStart) {
		this.runAtStart = runAtStart;
	}

	public String getRunTime() {
		return this.runTime;
	}

	public void setRunTime(String runTime) {
		this.runTime = runTime;
	}

	public String getTickPeriod() {
		return this.tickPeriod;
	}

	public void setTickPeriod(String tickPeriod) {
		this.tickPeriod = tickPeriod;
	}

	public Integer getTickTime() {
		return this.tickTime;
	}

	public void setTickTime(Integer tickTime) {
		this.tickTime = tickTime;
	}

	public String getWeekdays() {
		return this.weekdays;
	}

	public void setWeekdays(String weekdays) {
		this.weekdays = weekdays;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Integer enabled) {
		this.enabled = enabled;
	}

}
