package net.iretailer.model;
// Generated 2016-2-1 23:19:37 by Hibernate Tools 4.3.1.Final

/**
 * TBusinessTime generated by hbm2java
 */
public class TBusinessTime implements java.io.Serializable {

	private String id;
	private String timeType;
	private String startDate;
	private String endDate;
	private String weekdays;
	private String startTime;
	private String endTime;
	private String description;

	public TBusinessTime() {
	}

	public TBusinessTime(String id, String timeType, String startDate, String endDate, String startTime,
			String endTime) {
		this.id = id;
		this.timeType = timeType;
		this.startDate = startDate;
		this.endDate = endDate;
		this.startTime = startTime;
		this.endTime = endTime;
	}

	public TBusinessTime(String id, String timeType, String startDate, String endDate, String weekdays,
			String startTime, String endTime, String description) {
		this.id = id;
		this.timeType = timeType;
		this.startDate = startDate;
		this.endDate = endDate;
		this.weekdays = weekdays;
		this.startTime = startTime;
		this.endTime = endTime;
		this.description = description;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTimeType() {
		return this.timeType;
	}

	public void setTimeType(String timeType) {
		this.timeType = timeType;
	}

	public String getStartDate() {
		return this.startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public String getWeekdays() {
		return this.weekdays;
	}

	public void setWeekdays(String weekdays) {
		this.weekdays = weekdays;
	}

	public String getStartTime() {
		return this.startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return this.endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
