package net.iretailer.model;
// Generated 2016-2-1 23:19:37 by Hibernate Tools 4.3.1.Final

/**
 * THoliday generated by hbm2java
 */
public class THoliday implements java.io.Serializable {

	private String id;
	private String name;
	private String holiday;
	private String dayType;
	private Short isWorkday;

	public THoliday() {
	}

	public THoliday(String id, String name, String holiday, String dayType) {
		this.id = id;
		this.name = name;
		this.holiday = holiday;
		this.dayType = dayType;
	}

	public THoliday(String id, String name, String holiday, String dayType, Short isWorkday) {
		this.id = id;
		this.name = name;
		this.holiday = holiday;
		this.dayType = dayType;
		this.isWorkday = isWorkday;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getHoliday() {
		return this.holiday;
	}

	public void setHoliday(String holiday) {
		this.holiday = holiday;
	}

	public String getDayType() {
		return this.dayType;
	}

	public void setDayType(String dayType) {
		this.dayType = dayType;
	}

	public Short getIsWorkday() {
		return this.isWorkday;
	}

	public void setIsWorkday(Short isWorkday) {
		this.isWorkday = isWorkday;
	}

}
