package net.iretailer.model;
// Generated 2016-2-1 23:19:37 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TPack5Wifidetect generated by hbm2java
 */
public class TPack5Wifidetect implements java.io.Serializable {

	private Integer id;
	private int zoneId;
	private Date dateTime;
	private String date;
	private Short dateHour;
	private Short dateMin5;
	private Integer numMacDetected;
	private Integer numMacEnter;
	private Integer numMacEnterReturn;
	private Integer numMacEnterNew;

	public TPack5Wifidetect() {
	}

	public TPack5Wifidetect(int zoneId) {
		this.zoneId = zoneId;
	}

	public TPack5Wifidetect(int zoneId, Date dateTime, String date, Short dateHour, Short dateMin5,
			Integer numMacDetected, Integer numMacEnter, Integer numMacEnterReturn, Integer numMacEnterNew) {
		this.zoneId = zoneId;
		this.dateTime = dateTime;
		this.date = date;
		this.dateHour = dateHour;
		this.dateMin5 = dateMin5;
		this.numMacDetected = numMacDetected;
		this.numMacEnter = numMacEnter;
		this.numMacEnterReturn = numMacEnterReturn;
		this.numMacEnterNew = numMacEnterNew;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getZoneId() {
		return this.zoneId;
	}

	public void setZoneId(int zoneId) {
		this.zoneId = zoneId;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public Short getDateHour() {
		return this.dateHour;
	}

	public void setDateHour(Short dateHour) {
		this.dateHour = dateHour;
	}

	public Short getDateMin5() {
		return this.dateMin5;
	}

	public void setDateMin5(Short dateMin5) {
		this.dateMin5 = dateMin5;
	}

	public Integer getNumMacDetected() {
		return this.numMacDetected;
	}

	public void setNumMacDetected(Integer numMacDetected) {
		this.numMacDetected = numMacDetected;
	}

	public Integer getNumMacEnter() {
		return this.numMacEnter;
	}

	public void setNumMacEnter(Integer numMacEnter) {
		this.numMacEnter = numMacEnter;
	}

	public Integer getNumMacEnterReturn() {
		return this.numMacEnterReturn;
	}

	public void setNumMacEnterReturn(Integer numMacEnterReturn) {
		this.numMacEnterReturn = numMacEnterReturn;
	}

	public Integer getNumMacEnterNew() {
		return this.numMacEnterNew;
	}

	public void setNumMacEnterNew(Integer numMacEnterNew) {
		this.numMacEnterNew = numMacEnterNew;
	}

}
