package net.iretailer.model;
// Generated 2016-2-1 23:19:37 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TPack5Dwelltime generated by hbm2java
 */
public class TPack5Dwelltime implements java.io.Serializable {

	private Integer id;
	private int zoneId;
	private String date;
	private Short dateHour;
	private Short dateMin5;
	private Short numberServed;
	private Short secondsOccupied;
	private Date packTime;
	private Date updateTime;

	public TPack5Dwelltime() {
	}

	public TPack5Dwelltime(int zoneId) {
		this.zoneId = zoneId;
	}

	public TPack5Dwelltime(int zoneId, String date, Short dateHour, Short dateMin5, Short numberServed,
			Short secondsOccupied, Date packTime, Date updateTime) {
		this.zoneId = zoneId;
		this.date = date;
		this.dateHour = dateHour;
		this.dateMin5 = dateMin5;
		this.numberServed = numberServed;
		this.secondsOccupied = secondsOccupied;
		this.packTime = packTime;
		this.updateTime = updateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getZoneId() {
		return this.zoneId;
	}

	public void setZoneId(int zoneId) {
		this.zoneId = zoneId;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public Short getDateHour() {
		return this.dateHour;
	}

	public void setDateHour(Short dateHour) {
		this.dateHour = dateHour;
	}

	public Short getDateMin5() {
		return this.dateMin5;
	}

	public void setDateMin5(Short dateMin5) {
		this.dateMin5 = dateMin5;
	}

	public Short getNumberServed() {
		return this.numberServed;
	}

	public void setNumberServed(Short numberServed) {
		this.numberServed = numberServed;
	}

	public Short getSecondsOccupied() {
		return this.secondsOccupied;
	}

	public void setSecondsOccupied(Short secondsOccupied) {
		this.secondsOccupied = secondsOccupied;
	}

	public Date getPackTime() {
		return this.packTime;
	}

	public void setPackTime(Date packTime) {
		this.packTime = packTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
