package net.iretailer.model;
// Generated 2016-2-1 23:19:37 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TPackPassengerflow generated by hbm2java
 */
public class TPackPassengerflow implements java.io.Serializable {

	private Integer id;
	private int zoneId;
	private String date;
	private Short dateHour;
	private Short dateMinPeriod;
	private Short countEnter;
	private Short countExit;
	private Short period;
	private Date packTime;
	private Date updateTime;

	public TPackPassengerflow() {
	}

	public TPackPassengerflow(int zoneId) {
		this.zoneId = zoneId;
	}

	public TPackPassengerflow(int zoneId, String date, Short dateHour, Short dateMinPeriod, Short countEnter,
			Short countExit, Short period, Date packTime, Date updateTime) {
		this.zoneId = zoneId;
		this.date = date;
		this.dateHour = dateHour;
		this.dateMinPeriod = dateMinPeriod;
		this.countEnter = countEnter;
		this.countExit = countExit;
		this.period = period;
		this.packTime = packTime;
		this.updateTime = updateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getZoneId() {
		return this.zoneId;
	}

	public void setZoneId(int zoneId) {
		this.zoneId = zoneId;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public Short getDateHour() {
		return this.dateHour;
	}

	public void setDateHour(Short dateHour) {
		this.dateHour = dateHour;
	}

	public Short getDateMinPeriod() {
		return this.dateMinPeriod;
	}

	public void setDateMinPeriod(Short dateMinPeriod) {
		this.dateMinPeriod = dateMinPeriod;
	}

	public Short getCountEnter() {
		return this.countEnter;
	}

	public void setCountEnter(Short countEnter) {
		this.countEnter = countEnter;
	}

	public Short getCountExit() {
		return this.countExit;
	}

	public void setCountExit(Short countExit) {
		this.countExit = countExit;
	}

	public Short getPeriod() {
		return this.period;
	}

	public void setPeriod(Short period) {
		this.period = period;
	}

	public Date getPackTime() {
		return this.packTime;
	}

	public void setPackTime(Date packTime) {
		this.packTime = packTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
