package net.iretailer.model;
// Generated 2016-2-1 23:19:37 by Hibernate Tools 4.3.1.Final

/**
 * TPos generated by hbm2java
 */
public class TPos implements java.io.Serializable {

	private Integer id;
	private String storeId;
	private int physicalZoneId;
	private String posDate;
	private Integer dateHour;
	private Integer dateMin;
	private Integer dateMinPeriod;
	private Integer period;
	private String place;
	private Integer sales;
	private Integer tradesNumber;
	private Integer tradeGoodsNumber;
	private String updateTime;

	public TPos() {
	}

	public TPos(String storeId, int physicalZoneId) {
		this.storeId = storeId;
		this.physicalZoneId = physicalZoneId;
	}

	public TPos(String storeId, int physicalZoneId, String posDate, Integer dateHour, Integer dateMin,
			Integer dateMinPeriod, Integer period, String place, Integer sales, Integer tradesNumber,
			Integer tradeGoodsNumber, String updateTime) {
		this.storeId = storeId;
		this.physicalZoneId = physicalZoneId;
		this.posDate = posDate;
		this.dateHour = dateHour;
		this.dateMin = dateMin;
		this.dateMinPeriod = dateMinPeriod;
		this.period = period;
		this.place = place;
		this.sales = sales;
		this.tradesNumber = tradesNumber;
		this.tradeGoodsNumber = tradeGoodsNumber;
		this.updateTime = updateTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getStoreId() {
		return this.storeId;
	}

	public void setStoreId(String storeId) {
		this.storeId = storeId;
	}

	public int getPhysicalZoneId() {
		return this.physicalZoneId;
	}

	public void setPhysicalZoneId(int physicalZoneId) {
		this.physicalZoneId = physicalZoneId;
	}

	public String getPosDate() {
		return this.posDate;
	}

	public void setPosDate(String posDate) {
		this.posDate = posDate;
	}

	public Integer getDateHour() {
		return this.dateHour;
	}

	public void setDateHour(Integer dateHour) {
		this.dateHour = dateHour;
	}

	public Integer getDateMin() {
		return this.dateMin;
	}

	public void setDateMin(Integer dateMin) {
		this.dateMin = dateMin;
	}

	public Integer getDateMinPeriod() {
		return this.dateMinPeriod;
	}

	public void setDateMinPeriod(Integer dateMinPeriod) {
		this.dateMinPeriod = dateMinPeriod;
	}

	public Integer getPeriod() {
		return this.period;
	}

	public void setPeriod(Integer period) {
		this.period = period;
	}

	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	public Integer getSales() {
		return this.sales;
	}

	public void setSales(Integer sales) {
		this.sales = sales;
	}

	public Integer getTradesNumber() {
		return this.tradesNumber;
	}

	public void setTradesNumber(Integer tradesNumber) {
		this.tradesNumber = tradesNumber;
	}

	public Integer getTradeGoodsNumber() {
		return this.tradeGoodsNumber;
	}

	public void setTradeGoodsNumber(Integer tradeGoodsNumber) {
		this.tradeGoodsNumber = tradeGoodsNumber;
	}

	public String getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}

}
