package net.iretailer.model;
// Generated 2016-2-1 23:19:37 by Hibernate Tools 4.3.1.Final

/**
 * TrStoreBusinessTime generated by hbm2java
 */
public class TrStoreBusinessTime implements java.io.Serializable {

	private String id;
	private String storeId;
	private String timeId;

	public TrStoreBusinessTime() {
	}

	public TrStoreBusinessTime(String id, String storeId, String timeId) {
		this.id = id;
		this.storeId = storeId;
		this.timeId = timeId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getStoreId() {
		return this.storeId;
	}

	public void setStoreId(String storeId) {
		this.storeId = storeId;
	}

	public String getTimeId() {
		return this.timeId;
	}

	public void setTimeId(String timeId) {
		this.timeId = timeId;
	}

}
