package net.iretailer.model;
// Generated 2016-2-1 23:19:37 by Hibernate Tools 4.3.1.Final

/**
 * TrStoreActivity generated by hbm2java
 */
public class TrStoreActivity implements java.io.Serializable {

	private String id;
	private String storeId;
	private String activityId;

	public TrStoreActivity() {
	}

	public TrStoreActivity(String id, String storeId, String activityId) {
		this.id = id;
		this.storeId = storeId;
		this.activityId = activityId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getStoreId() {
		return this.storeId;
	}

	public void setStoreId(String storeId) {
		this.storeId = storeId;
	}

	public String getActivityId() {
		return this.activityId;
	}

	public void setActivityId(String activityId) {
		this.activityId = activityId;
	}

}
