package net.iretailer.model;
// Generated 2016-2-1 23:19:37 by Hibernate Tools 4.3.1.Final

/**
 * TWeather generated by hbm2java
 */
public class TWeather implements java.io.Serializable {

	private TWeatherId id;

	public TWeather() {
	}

	public TWeather(TWeatherId id) {
		this.id = id;
	}

	public TWeatherId getId() {
		return this.id;
	}

	public void setId(TWeatherId id) {
		this.id = id;
	}

}
