package net.iretailer.model;
// Generated 2016-2-1 23:19:37 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * TWifidetecthour generated by hbm2java
 */
public class TWifidetecthour implements java.io.Serializable {

	private Integer id;
	private int zoneId;
	private String macDetected;
	private Date dateTime;
	private Short dateHour;
	private Short visitTimes;
	private Short duration;

	public TWifidetecthour() {
	}

	public TWifidetecthour(int zoneId) {
		this.zoneId = zoneId;
	}

	public TWifidetecthour(int zoneId, String macDetected, Date dateTime, Short dateHour, Short visitTimes,
			Short duration) {
		this.zoneId = zoneId;
		this.macDetected = macDetected;
		this.dateTime = dateTime;
		this.dateHour = dateHour;
		this.visitTimes = visitTimes;
		this.duration = duration;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getZoneId() {
		return this.zoneId;
	}

	public void setZoneId(int zoneId) {
		this.zoneId = zoneId;
	}

	public String getMacDetected() {
		return this.macDetected;
	}

	public void setMacDetected(String macDetected) {
		this.macDetected = macDetected;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public Short getDateHour() {
		return this.dateHour;
	}

	public void setDateHour(Short dateHour) {
		this.dateHour = dateHour;
	}

	public Short getVisitTimes() {
		return this.visitTimes;
	}

	public void setVisitTimes(Short visitTimes) {
		this.visitTimes = visitTimes;
	}

	public Short getDuration() {
		return this.duration;
	}

	public void setDuration(Short duration) {
		this.duration = duration;
	}

}
