package net.iretailer.model;
// Generated 2016-2-1 23:19:37 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Zone generated by hbm2java
 */
public class Zone implements java.io.Serializable {

	private Integer id;
	private Integer physicalZoneId;
	private String name;
	private Integer deviceId;
	private short deviceZoneId;
	private Date createDate;
	private Short enable;
	private String zoneClass;

	public Zone() {
	}

	public Zone(short deviceZoneId) {
		this.deviceZoneId = deviceZoneId;
	}

	public Zone(Integer physicalZoneId, String name, Integer deviceId, short deviceZoneId, Date createDate,
			Short enable, String zoneClass) {
		this.physicalZoneId = physicalZoneId;
		this.name = name;
		this.deviceId = deviceId;
		this.deviceZoneId = deviceZoneId;
		this.createDate = createDate;
		this.enable = enable;
		this.zoneClass = zoneClass;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getPhysicalZoneId() {
		return this.physicalZoneId;
	}

	public void setPhysicalZoneId(Integer physicalZoneId) {
		this.physicalZoneId = physicalZoneId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(Integer deviceId) {
		this.deviceId = deviceId;
	}

	public short getDeviceZoneId() {
		return this.deviceZoneId;
	}

	public void setDeviceZoneId(short deviceZoneId) {
		this.deviceZoneId = deviceZoneId;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Short getEnable() {
		return this.enable;
	}

	public void setEnable(Short enable) {
		this.enable = enable;
	}

	public String getZoneClass() {
		return this.zoneClass;
	}

	public void setZoneClass(String zoneClass) {
		this.zoneClass = zoneClass;
	}

}
