package com.openscoring.mgr.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * PmmlFeature generated by hbm2java
 */
public class PmmlFeature implements Serializable {

	private String uuid;
	private String pmmlHisUuid;
	private String featureName;
	private String featureCode;
	private String featureDesc;
	private Date lastModifiedTime;
	private String lastModifiedBy;

	public PmmlFeature() {
	}

	public PmmlFeature(String uuid) {
		this.uuid = uuid;
	}

	public PmmlFeature(String uuid, String pmmlHisUuid, String featureName, String featureCode, String featureDesc,
			Date lastModifiedTime, String lastModifiedBy) {
		this.uuid = uuid;
		this.pmmlHisUuid = pmmlHisUuid;
		this.featureName = featureName;
		this.featureCode = featureCode;
		this.featureDesc = featureDesc;
		this.lastModifiedTime = lastModifiedTime;
		this.lastModifiedBy = lastModifiedBy;
	}

	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public String getPmmlHisUuid() {
		return this.pmmlHisUuid;
	}

	public void setPmmlHisUuid(String pmmlHisUuid) {
		this.pmmlHisUuid = pmmlHisUuid;
	}

	public String getFeatureName() {
		return this.featureName;
	}

	public void setFeatureName(String featureName) {
		this.featureName = featureName;
	}

	public String getFeatureCode() {
		return this.featureCode;
	}

	public void setFeatureCode(String featureCode) {
		this.featureCode = featureCode;
	}

	public String getFeatureDesc() {
		return this.featureDesc;
	}

	public void setFeatureDesc(String featureDesc) {
		this.featureDesc = featureDesc;
	}

	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

}
