package com.openscoring.mgr.entity;

import java.util.Date;

/**
 * Pmml generated by hbm2java
 */
public class Pmml implements java.io.Serializable {

	private String uuid;
	private String version;
	private String projectId;
	private String code;
	private String name;
	private Date effectDate;
	private String modelDesc;
	private Date lastModifiedTime;
	private String lastModifiedBy;
	private String content;

	public Pmml() {
	}

	public Pmml(String uuid) {
		this.uuid = uuid;
	}

	public Pmml(String uuid, String projectId, String code, String name, Date effectDate, String modelDesc,
			Date lastModifiedTime, String lastModifiedBy, String content) {
		this.uuid = uuid;
		this.projectId = projectId;
		this.code = code;
		this.name = name;
		this.effectDate = effectDate;
		this.modelDesc = modelDesc;
		this.lastModifiedTime = lastModifiedTime;
		this.lastModifiedBy = lastModifiedBy;
		this.content = content;
	}

	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getEffectDate() {
		return this.effectDate;
	}

	public void setEffectDate(Date effectDate) {
		this.effectDate = effectDate;
	}

	public String getModelDesc() {
		return this.modelDesc;
	}

	public void setModelDesc(String modelDesc) {
		this.modelDesc = modelDesc;
	}

	public Date getLastModifiedTime() {
		return this.lastModifiedTime;
	}

	public void setLastModifiedTime(Date lastModifiedTime) {
		this.lastModifiedTime = lastModifiedTime;
	}

	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
