package com.openscoring.mgr.entity;

import java.util.Date;

/**
 * PmmlExecLog generated by hbm2java
 */
public class PmmlExecLog implements java.io.Serializable {

	private String uuid;
	private String pmmlHisId;
	private Date execStartTime;
	private String featureValue;
	private String execDuration;

	public PmmlExecLog() {
	}

	public PmmlExecLog(String uuid) {
		this.uuid = uuid;
	}

	public PmmlExecLog(String uuid, String pmmlHisId, Date execStartTime, String featureValue, String execDuration) {
		this.uuid = uuid;
		this.pmmlHisId = pmmlHisId;
		this.execStartTime = execStartTime;
		this.featureValue = featureValue;
		this.execDuration = execDuration;
	}

	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public String getPmmlHisId() {
		return this.pmmlHisId;
	}

	public void setPmmlHisId(String pmmlHisId) {
		this.pmmlHisId = pmmlHisId;
	}

	public Date getExecStartTime() {
		return this.execStartTime;
	}

	public void setExecStartTime(Date execStartTime) {
		this.execStartTime = execStartTime;
	}

	public String getFeatureValue() {
		return this.featureValue;
	}

	public void setFeatureValue(String featureValue) {
		this.featureValue = featureValue;
	}

	public String getExecDuration() {
		return this.execDuration;
	}

	public void setExecDuration(String execDuration) {
		this.execDuration = execDuration;
	}

}
